### ISSUE TITLE
Documentation unclear on how to add other collections to a 'community'

### ISSUE THREAD

**Issue by jetlej** [reservoirprotocol/marketplace#393]
I see that you have to add slugs to the `NEXT_PUBLIC_COMMUNITY`, but where are those slugs registered? OpenSea? Reservoir? 

I've tried many permutations, but nothing shows in the resulting search bar.

**Comment by pedromcunha** [comment]
If you want to create a 'community', you need to use the collection set api to group a set of collection addresses. https://docs.reservoir.tools/reference/postcollectionssetsv1

That API returns a `collectionsSetId` which you can then use to configure the marketplace. `NEXT_PUBLIC_COLLECTION_SET_ID`, this is the env variable that you'll need to set in order to configure your marketplace correctly.
